// AUTO-GENERATED by scripts/build-catch-unicorn.mjs — do not edit by hand.
export const CATCH_UNICORN_KEY = "catchUnicorn";
export const CATCH_UNICORN_SHEET = "catch-unicorn/sheet.png";
export const CATCH_UNICORN_ANIM = "catch-fly";
export const CATCH_UNICORN = {
  frameWidth: 256,
  frameHeight: 256,
  frameCount: 48,
  frameRate: 24,
} as const;
