// AUTO-GENERATED by scripts/build-emoji.mjs — do not edit by hand.
// Source: Google Noto animated emoji (https://googlefonts.github.io/noto-emoji-animation/), Apache-2.0.
export interface EmojiDef {
  key: string;
  sheet: string;
  anim: string;
  frameWidth: number;
  frameHeight: number;
  frameCount: number;
  frameRate: number;
}

export const EMOJI: Record<string, EmojiDef> = {
  cloud: { key: "emoji-cloud", sheet: "emoji/cloud.png", anim: "emoji-cloud", frameWidth: 72, frameHeight: 72, frameCount: 24, frameRate: 13 },
  star: { key: "emoji-star", sheet: "emoji/star.png", anim: "emoji-star", frameWidth: 72, frameHeight: 72, frameCount: 24, frameRate: 11 },
  icecream: { key: "emoji-icecream", sheet: "emoji/icecream.png", anim: "emoji-icecream", frameWidth: 72, frameHeight: 72, frameCount: 24, frameRate: 7 },
  balloon: { key: "emoji-balloon", sheet: "emoji/balloon.png", anim: "emoji-balloon", frameWidth: 72, frameHeight: 72, frameCount: 24, frameRate: 17 },
  heart: { key: "emoji-heart", sheet: "emoji/heart.png", anim: "emoji-heart", frameWidth: 72, frameHeight: 72, frameCount: 24, frameRate: 27 },
  flower: { key: "emoji-flower", sheet: "emoji/flower.png", anim: "emoji-flower", frameWidth: 72, frameHeight: 72, frameCount: 24, frameRate: 7 },
  donut: { key: "emoji-donut", sheet: "emoji/donut.png", anim: "emoji-donut", frameWidth: 72, frameHeight: 72, frameCount: 24, frameRate: 6 },
  butterfly: { key: "emoji-butterfly", sheet: "emoji/butterfly.png", anim: "emoji-butterfly", frameWidth: 72, frameHeight: 72, frameCount: 24, frameRate: 10 },
  gem: { key: "emoji-gem", sheet: "emoji/gem.png", anim: "emoji-gem", frameWidth: 72, frameHeight: 72, frameCount: 24, frameRate: 20 },
  cupcake: { key: "emoji-cupcake", sheet: "emoji/cupcake.png", anim: "emoji-cupcake", frameWidth: 72, frameHeight: 72, frameCount: 24, frameRate: 15 },
  lollipop: { key: "emoji-lollipop", sheet: "emoji/lollipop.png", anim: "emoji-lollipop", frameWidth: 72, frameHeight: 72, frameCount: 24, frameRate: 9 },
};

export const EMOJI_DEFS: EmojiDef[] = Object.values(EMOJI);
