// AUTO-GENERATED by scripts/build-emoji.mjs — do not edit by hand.
// Source: Google Noto animated emoji (https://googlefonts.github.io/noto-emoji-animation/), Apache-2.0.
export interface EmojiDef {
  key: string;
  sheet: string;
  anim: string;
  frameWidth: number;
  frameHeight: number;
  frameCount: number;
  frameRate: number;
}

export const EMOJI: Record<string, EmojiDef> = {
  cloud: { key: "emoji-cloud", sheet: "emoji/cloud.png", anim: "emoji-cloud", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 13 },
  star: { key: "emoji-star", sheet: "emoji/star.png", anim: "emoji-star", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 11 },
  icecream: { key: "emoji-icecream", sheet: "emoji/icecream.png", anim: "emoji-icecream", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 7 },
  balloon: { key: "emoji-balloon", sheet: "emoji/balloon.png", anim: "emoji-balloon", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 17 },
  heart: { key: "emoji-heart", sheet: "emoji/heart.png", anim: "emoji-heart", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 27 },
  flower: { key: "emoji-flower", sheet: "emoji/flower.png", anim: "emoji-flower", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 7 },
  donut: { key: "emoji-donut", sheet: "emoji/donut.png", anim: "emoji-donut", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 6 },
  butterfly: { key: "emoji-butterfly", sheet: "emoji/butterfly.png", anim: "emoji-butterfly", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 10 },
  gem: { key: "emoji-gem", sheet: "emoji/gem.png", anim: "emoji-gem", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 20 },
  cupcake: { key: "emoji-cupcake", sheet: "emoji/cupcake.png", anim: "emoji-cupcake", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 15 },
  lollipop: { key: "emoji-lollipop", sheet: "emoji/lollipop.png", anim: "emoji-lollipop", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 9 },
  cat: { key: "emoji-cat", sheet: "emoji/cat.png", anim: "emoji-cat", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 9 },
  fox: { key: "emoji-fox", sheet: "emoji/fox.png", anim: "emoji-fox", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 13 },
  bear: { key: "emoji-bear", sheet: "emoji/bear.png", anim: "emoji-bear", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 15 },
  panda: { key: "emoji-panda", sheet: "emoji/panda.png", anim: "emoji-panda", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 10 },
  lion: { key: "emoji-lion", sheet: "emoji/lion.png", anim: "emoji-lion", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 11 },
  cow: { key: "emoji-cow", sheet: "emoji/cow.png", anim: "emoji-cow", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 15 },
  sloth: { key: "emoji-sloth", sheet: "emoji/sloth.png", anim: "emoji-sloth", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 6 },
  otter: { key: "emoji-otter", sheet: "emoji/otter.png", anim: "emoji-otter", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 9 },
  raccoon: { key: "emoji-raccoon", sheet: "emoji/raccoon.png", anim: "emoji-raccoon", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 8 },
  hedgehog: { key: "emoji-hedgehog", sheet: "emoji/hedgehog.png", anim: "emoji-hedgehog", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 12 },
  octopus: { key: "emoji-octopus", sheet: "emoji/octopus.png", anim: "emoji-octopus", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 17 },
  turtle: { key: "emoji-turtle", sheet: "emoji/turtle.png", anim: "emoji-turtle", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 8 },
  whale: { key: "emoji-whale", sheet: "emoji/whale.png", anim: "emoji-whale", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 10 },
  crab: { key: "emoji-crab", sheet: "emoji/crab.png", anim: "emoji-crab", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 10 },
  penguin: { key: "emoji-penguin", sheet: "emoji/penguin.png", anim: "emoji-penguin", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 6 },
  chick: { key: "emoji-chick", sheet: "emoji/chick.png", anim: "emoji-chick", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 9 },
  owl: { key: "emoji-owl", sheet: "emoji/owl.png", anim: "emoji-owl", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 9 },
  frog: { key: "emoji-frog", sheet: "emoji/frog.png", anim: "emoji-frog", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 7 },
  snail: { key: "emoji-snail", sheet: "emoji/snail.png", anim: "emoji-snail", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 10 },
  trex: { key: "emoji-trex", sheet: "emoji/trex.png", anim: "emoji-trex", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 17 },
  sauropod: { key: "emoji-sauropod", sheet: "emoji/sauropod.png", anim: "emoji-sauropod", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 8 },
  robot: { key: "emoji-robot", sheet: "emoji/robot.png", anim: "emoji-robot", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 10 },
  alien: { key: "emoji-alien", sheet: "emoji/alien.png", anim: "emoji-alien", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 25 },
  ghost: { key: "emoji-ghost", sheet: "emoji/ghost.png", anim: "emoji-ghost", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 11 },
  poop: { key: "emoji-poop", sheet: "emoji/poop.png", anim: "emoji-poop", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 11 },
  dog: { key: "emoji-dog", sheet: "emoji/dog.png", anim: "emoji-dog", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 11 },
  rabbit: { key: "emoji-rabbit", sheet: "emoji/rabbit.png", anim: "emoji-rabbit", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 20 },
  monkey: { key: "emoji-monkey", sheet: "emoji/monkey.png", anim: "emoji-monkey", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 15 },
  pig: { key: "emoji-pig", sheet: "emoji/pig.png", anim: "emoji-pig", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 7 },
  tiger: { key: "emoji-tiger", sheet: "emoji/tiger.png", anim: "emoji-tiger", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 6 },
  horse: { key: "emoji-horse", sheet: "emoji/horse.png", anim: "emoji-horse", frameWidth: 144, frameHeight: 144, frameCount: 16, frameRate: 30 },
  goat: { key: "emoji-goat", sheet: "emoji/goat.png", anim: "emoji-goat", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 13 },
  ox: { key: "emoji-ox", sheet: "emoji/ox.png", anim: "emoji-ox", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 8 },
  rat: { key: "emoji-rat", sheet: "emoji/rat.png", anim: "emoji-rat", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 10 },
  gorilla: { key: "emoji-gorilla", sheet: "emoji/gorilla.png", anim: "emoji-gorilla", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 10 },
  orangutan: { key: "emoji-orangutan", sheet: "emoji/orangutan.png", anim: "emoji-orangutan", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 7 },
  kangaroo: { key: "emoji-kangaroo", sheet: "emoji/kangaroo.png", anim: "emoji-kangaroo", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 17 },
  seal: { key: "emoji-seal", sheet: "emoji/seal.png", anim: "emoji-seal", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 10 },
  chipmunk: { key: "emoji-chipmunk", sheet: "emoji/chipmunk.png", anim: "emoji-chipmunk", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 9 },
  peacock: { key: "emoji-peacock", sheet: "emoji/peacock.png", anim: "emoji-peacock", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 20 },
  rooster: { key: "emoji-rooster", sheet: "emoji/rooster.png", anim: "emoji-rooster", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 9 },
  eagle: { key: "emoji-eagle", sheet: "emoji/eagle.png", anim: "emoji-eagle", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 20 },
  flamingo: { key: "emoji-flamingo", sheet: "emoji/flamingo.png", anim: "emoji-flamingo", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 7 },
  dove: { key: "emoji-dove", sheet: "emoji/dove.png", anim: "emoji-dove", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 8 },
  snake: { key: "emoji-snake", sheet: "emoji/snake.png", anim: "emoji-snake", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 8 },
  lizard: { key: "emoji-lizard", sheet: "emoji/lizard.png", anim: "emoji-lizard", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 16 },
  lobster: { key: "emoji-lobster", sheet: "emoji/lobster.png", anim: "emoji-lobster", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 15 },
  jellyfish: { key: "emoji-jellyfish", sheet: "emoji/jellyfish.png", anim: "emoji-jellyfish", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 11 },
  ant: { key: "emoji-ant", sheet: "emoji/ant.png", anim: "emoji-ant", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 7 },
  microbe: { key: "emoji-microbe", sheet: "emoji/microbe.png", anim: "emoji-microbe", frameWidth: 144, frameHeight: 144, frameCount: 24, frameRate: 22 },
};

export const EMOJI_DEFS: EmojiDef[] = Object.values(EMOJI);
